baseurl = "../"
DefaultContentLanguage = "en"
title = "Data Se"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
googleAnalytics = "UA-99297878-1"
disqusShortname = "https-sebastiansauer-github-io"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true


[Params]
  subtitle = "Data Science Blog of Sebastian Sauer"
  logo = "img/logo-data-se.png"
  favicon = "img/logo-data-se.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"

[permalinks]
    post = "/:year/:month/:day/:slug/"


[Author]
  name = "Sebastiuan Sauer"
  website = "yourwebsite.com"
  email = "ssauer@posteo.de"
  github = "sebastian_sauer"
  twitter = "sauer_sebasitan"
  reddit = "username"
  linkedin = "https://www.linkedin.com/in/dr-sebastian-sauer-4791762/"
  xing = "https://www.xing.com/profile/Sebastian_Sauer2"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 2

[taxonomies]
  category = "categories"
  tag = "tags"
