baseurl = "https://sebastiansauer.github.io/data_se/"
languageCode = "en-us"
title = "Data Se"
theme = "hugo-lithium-theme"
disqusShortname = "https-data-se-netlify-com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
#before_chapter_script = "_common.R"
enableEmoji = true


[params]
    author = "Sebastian Sauer"
    dateFormat = "2006/01/02"
    description = "Sebastian Sauer's Data Science Blog"

    highlightjsVersion = "11.9.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

[params.logo]
    url = "logo-data-se.png"
    width = 50
    height = 50
    alt = "Logo"


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"

[[menu.main]]
    name = "Blog"
    url = "/"

[[menu.main]]
    name = "Data privacy"
    url = "/privacy/"


[social]
    github  = "https://github.com/sebastian_sauer"

[markup]
  [markup.highlight]
    style = "github"
    noClasses = true
    lineNos = false
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = false
        title = false
