baseurl = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Data Se"
subtitle = "Data Science Blog of Sebastian Sauer"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
googleAnalytics = "UA-99297878-1"
disqusShortname = "https-sebastiansauer-github-io"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/sebastiansauer"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/sauer_sebastian"

[params]
    description = "A blog on data science topics, basically a notebook of current thoughts"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = img/avatar-icon.png
    width = 50
    height = 50
    alt = "Logo"
