---
title: My favorite stats text book
author: Sebastian Sauer
date: '2017-11-27'
slug: my-favorite-stats-text-book
categories:
  - rstats
tags:
  - teaching
  - rstats
---


Some thoughts how my favorite *applied* stats text book  would look like. I am looking at eg., business fields such as MBA as consumers.


## My ideal applied stats text book


1. is case study oriented ("Assume you would like to predict which movie will score highest next year based on some movie characteristics you know")

2. makes use of recent data analytics techniques such as tree based methods (Random Forests) or Shrinkage models (Lasso)

3. does not stop at explaining p-values and t-tests (which are of limited use in the real world)

4. show alternatives to the p-value, in fact does not make much use of p-values

5. introduces Bayes stats thoroughly

6. focus on the needs of the business world, not (primarily) on the stats needs of academia

7. is highly visually oriented, shows how to produce beautiful and effective data visualizations

8. is technology savy, does not ignore the plethora of new technologies out there from JavaScript libraries, to RMarkdown, Shiny, Docker, Github, parallel computing, big queries, and more

9. is fully reproducible, values open science

10. is fun to read.


This list is certainly up for thought updates. Let me know how your fav text book looks like.




