---
title: Convenient way to cite blog posts using Bibtex
author: Sebastian Sauer
date: '2018-04-11'
slug: convenient-way-to-cite-blog-posts-using-bibtex
categories:
  - latex
tags:
  - tutorial
---


Writing (scholarly) texts - a great way is using Markdown. Bibtext interacts nicely with Markdown, so one can easily cite literature.

One question that came up for me a couple of times recently was how to cite blogs in Bibtex?

I found this solution to be the most convenient:


```
@misc{stats_test,
	Author = {Sebastian Sauer},
	Date-Added = {2018-03-29 13:54:38 +0000},
	Date-Modified = {2018-03-29 13:55:51 +0000},
	Doi = {10.17605/OSF.IO/SJHUY},
	Howpublished = {Data Set},
	Month = {01},
	Title = {Results from an exam in inferential statistics},
Year = {2017}}
```


The important points are the `@misc` class, and the `Howpublished` field. Rendering this citation yields (in APA form):

Sauer, S. (2017, Januar). Results from an exam in inferential statistics. Data Set. doi:10.17605/OSF.IO/SJHUY

Which appears to me as a sensible solution. Note the inclusion of "Data set." which is triggered by the `Howpublished` field. Previously I have been missing out this field when citing blogs, or more generally, web content.

It may well be that there are other and better approaches around, so inform me if you find some easier or prettier way.

