---
title: 'Playing around with dataviz: Showing correlations'
author: Sebastian Sauer
date: '2018-05-18'
slug: playing-around-with-dataviz-showing-correlations
categories:
  - dataviz
tags:
  - rstats
  - plotting
---


In this plot, we are looking into some ways of displaying association between (two) quantitative variables, aka correlation. Our goal is to present a rich representation of the correlation.

Let's take the dataset `flights` as an example.


```{r message = FALSE}
data(flights, package = "nycflights13")
library(tidyverse)
library(viridis)
```


```{r}
flights %>% 
  filter(arr_delay < 100, dep_delay < 100) %>% 
  ggplot(aes(x = dep_delay, y = arr_delay, color = origin)) +
  geom_point(alpha = .01) +
  geom_smooth(se = FALSE, color = "grey20") +
  geom_rug() +
  facet_wrap(~origin) +
  scale_color_viridis_d()
```

Points are not the only geom that make sense here. Let's try some more, e.g., `geom_hex()`.

```{r}
flights %>% 
  filter(arr_delay < 100, dep_delay < 100) %>% 
  ggplot(aes(x = dep_delay, y = arr_delay)) +
  geom_hex() +
  geom_smooth(se = FALSE, color = "grey20") +
  geom_rug() +
  facet_wrap(~origin) +
  scale_color_viridis_d()
```
