---
title: Force bibtex to show the exact date
author: Sebastian Sauer
date: '2018-12-29'
slug: force-bibtex-to-show-the-exact-date
categories:
  - rstats
tags:
  - RMarkdown
---


Citing (aka scientific citation) is quite straight forward in RMarkdown. However, there are some shortcomings. Primarily, as citations are rendered via Pandoc's reference engine, bibtex is used as a standard. Though is quite commonly used, bibtex has been, over and above, replaced by biblatex. biblatex is much more straight forward than bibtex (as text is formatted using latex and not bibtex, still making use of bibtex for the collection of references).

One simple way is to tell pandoc or RMkarkdown, for that matter, to use biblatex, see [this post](https://data-se.netlify.com/2018/12/28/using-biblatex-instead-of-bibtex-in-rmarkdown-for-finer-control/) for that approach. However, there are some tweaks that allow to continue using bibtex. 

For example, say you would like to show the exact date of one article; in standard bibtex it is not possible. However, the "month" field can be (ab)used for that pupose (this idea was found in [this post](https://libguides.nps.edu/citation/ieeebibtex), thanks for pointing out!).

Consider this bibtex input:

```
@electronic{martin_2014,
  author        = "J. Martin",
  title         = "Senator quits Montana race after charge of plagiarism",
  journal       = "New York Times",
  year          = "2014",
  month         = "Aug. 7",
  url           = "http://www.nytimes.com/2014/08/08/us/politics/john-walsh-drops-campaign-under-pressure-
from-democrats.html?_r=0",
}
```

It will be rendered (in APA) in this format:


>    Martin, J. (2014, Aug. 7). Senator quits montana race after charge of plagiarism. New York Times. Retrieved from http://www.nytimes.com/2014/08/08/us/politics/john-walsh-drops-campaign-under-pressure- from-democrats.html?_r=0



(Plus italics in the appropriate place)



# Drawback

However, note that the `electionic` type does not support pages. Conversely, the `article` type does not support the monhth field. So, in sum, this approach is far from perfect.


For instance, this bibtex input:

```
@article{wang_2014,
  author        = "W. Q. Wang and H. Shao",
  title         = "High altitude platform multichannel {SAR} for wide-area and staring imaging",
  journal       = "Aerosp. and Electron. Syst.",
  volume        = "29",
  number        = "25",
  month         = "Mar 10",
  year          = "2014",
  pages         = "12--17"
}
```

Will render like this:

>    Wang, W. Q., & Shao, H. (2014). High altitude platform multichannel SAR for wide-area and staring imaging. Aerosp. and Electron. Syst., 29(25), 12–17.




# Outro

In sum, changing to biblatex seems to be the only sensible approach if one needs fine control of referencing options.



