---
title: Emails schreiben an Dozierende
author: Sebastian Sauer
date: '2019-02-28'
slug: emails-schreiben-an-dozierende
categories:
  - teaching
tags:
  - German
  - teaching
---



E-Mails schreiben ist eine wesentliche Form der Korrespondenz mit eigenen Vorteilen und Schwächen. Jedenfalls ist sie allgegenwärtig. Dieser Beitrag soll (meinen) Studierenden Orientierung geben, wie man eine E-mail an Dozierende schreibt. Natürlich ist das meine Sicht der Dinge; andere Dozierende möchten vielleicht ein andere Art von E-Mails erhalten. 

Letztlich ist die Art von E-Mails an Dozierende nichts anderes als eine Form der Geschäftskorrespondenz. Daher gelten die entsprechenden Regeln; allerdings behält sich die akademische Welt vielleicht ein paar Feinheiten (und Freiheiten) vor, die man kennen sollten, wenn man solche Mails schreiben will oder muss. Viele Dozenten (m/w) bekommen sehr viele Mails, so dass es für sie wichtig ist, keine unnötigen Mails, keine weitschweifigen Mails oder Mails mit unpräzisen Fragen zu lesen.

## (Wann) sollte man eine Mail schreiben? 

Das ist die erste Frage, die man sich als Student (w/m) explizit stellen sollte. Meine Erfahrung ist, dass ich einige Mails erhalte, deren Antwort ich an geeigneter Stelle (Skript oder in einem Hinweisdokument) aufgeschrieben habe. Bitte lesen Sie also zuerst an geeigneter Stelle nach, bevor Sie eine Mail schreiben. Es hilft Ihnen oft auch, einen Kommilitonen anzusprechen ("Weißt du, ob wir die Arbeit ausgedruckt abgeben müssen?"). Finden Sie nach einiger Recherche keine Antwort, ist es angebracht, den Dozenten (m/w) in geeignter Form anzusprechen.  


## Oder besser die Frage ins Forum posten?

Sofern der Dozent ein Forum für Fragen Ihrer Gruppe/Klasse bereit gestellt hat, überleben Sie, ob Ihre Frage von allgemeinem Interesse ist. Oft ist das der Fall. Fragen wie "Sollen wir die Arbeit ausgedruckt abgeben?" oder "Wie laufen Nachholprüfungen ab?" sind von allgemeinem Interesse. Neben organisatorischen Fragen wie zu den Prüfungsleistungen sind fachliche Fragen von allgemeinem Interesse ("Wozu braucht man noch mal mal Statistik?"). Rein individuelle Fragen sind z.B. "Kann ich am Dienstag nach der Vorlesung mit Ihnen wg. XXX sprechen?".


## Lieber persönlich mit dem Dozenten sprechen?

Als Faustregel gilt: Fragen, die man prägnant (kurz und bündig) beantworten kann, eignen sich für Mails oder Posts ("Brauchen wir einen Computer morgen im Unterricht?"). Weniger scharf formulierte Fragen sollten besser persönlich besprochen werden ("Was sagt mir eigentlich der p-Wert?"). Sprechen Sie für solche Fragen den Dozenten zu geeigneter Zeit an (vor oder nach dem Unterricht oder in der Pause) oder schicken Sie eine Mail mit der Bitte um einen Termin.


## Wie spricht man sie/ihn an?

Wie bei geschäftlicher Korrespondenz gilt: Je weniger man den Gesprächspartner kennt, desto förmlicher sollte man formulieren. Im Zweifel lieber zu förmlich als zu jovial. Wenn Sie davon ausgehen, dass der Dozent Ihren Namen nicht mit einem Gesicht verbindet, bleiben Sie lieber bei "Sehr geehrter Herr XXX". Übrigens: Gehen Sie nicht davon aus, dass der Dozent Ihr Gesicht einordnen kann, wenn er Sie nur aus der Vorlesung kennt. Wie steht es mit dem akdemischen Titel des Dozenten? Muss der genannt werden? Einige Menschen bestehen darauf, dass ihr Titel in der Schriftform und vielleicht sogar in der mündlichen Anrede angeführt wird. Diesen Wunsche sollte man respektieren. Dann könnten Sie schreiben "Sehr geehrte Frau Professor Süß, ...". Professoren sind praktisch immer auch Doktoren (führen einen Doktortitel), wegen dieser Selbstverständlichkeit kann man auf das "Dr." verzichten (es sei denn, diese Person legt großen Wert darauf). Übrigens ist ein Professorentitel primär eine Funktionsbezeichnung, kein akademischer Grad. Akademische Studienabschlüsse werden in der Anrede nicht genannt.

Ist die Empfängerin promoviert, so schreiben Sie "Sehr geehrte Frau Dr. Mustermann". Schreibt der Dozent weniger formell zurück, etwa "Lieber Herr XXX", so können Sie die Form natürlich übernehmen. 

Ich persönlich kann darauf verzichten, dass Sie meinen Titel in Schriftform und auch in mündlicher Form nennen; viele andere Hochschullehrer (nicht alle!) sehen das auch so. Wenn Sie mich nicht näher kennen, schreiben Sie also "Sehr geehrter Herr Sauer" oder "Guten Tag Herr Sauer. Hat man einige Mails ausgetauscht, sich persönlich (und einvernehmlich) gesprochen, so ist es für mich in Ordnung mit "Hallo Herr Sauer" angesprochen zu werden.



## Wie formuliert man sein Anliegen?

Formulieren Sie eine präzise Frage, das ist wichtig. Unpräzise Fragen kosten unnötig Zeit und zeugen nicht von Überlegtheit. Unpräzise Fragen wären etwa: "Mein R funktioniert nicht, warum?" oder "Schauen Sie bitte mal, ist das ok so?" oder "Was muss ich bei der Themenwahl beachten?". Fügen Sie evtl. hinzu, dass Sie die Antwort nicht im Skript o.Ä. gefunden haben und Ihre Recherche keinen Erfolg hatte. Fassen Sie sich kurz. Nutzen Sie die Betreffzeile, um Ihr Anliegen prägnant zu formulieren. Prägnante Betreffzeilen sind z.B. "Anfrage für einen Gesprächstermin" oder "Benötigen wir einen Computer in der nächsten Stunde?". Geben Sie an, um welchen Kurs es sich handelt (bzw. in welchem Kurs sie eingetragen sind), damit der Empfänger Ihnen genaue Auskunft geben kann. Erwarten Sie, dass der Empfänger etwas tut, formulieren Sie das klar (aber höflich), etwa "Könnten Sie bitte noch die Fallstudie zu XXX einstellen?".



## Was sind grobe Fehler in einem Anschreiben an den Dozenten?

Der häufigste Fehler, den ich erlebe ist, dass ich die Antwort zu einer organisatorischen Frage im Skript (oder anderen zugänglichen Dokumenten) aufgeschrieben habe, aber der oder die Schreibende das nicht gelesen hatte. Typische Beispiele dieser Art sind: "Müssen wir die Arbeit ausgedruckt einreichen?" oder "Wie laufen Wiederholungsprüfungen ab?". Daher ist der wichtigste Punkt für Sie, als Schreibende(r), vorab zu schauen, ob die Antwort schon vorliegt (z.B. im Skript).

Weiterhin gilt es, ein Gespür für die Form zu wahren. So ist als Grußformel "Liebe Grüße, Michi" nicht akzeptabel. Gut sind Grußformeln wie "Beste Grüße Michael Mustermann" oder "Freundliche Grüße" oder auch "(Viele) Grüße". Für Sie wie für mich wie für alle gilt es, die Form zu wahren und höflich zu schreiben. Es braucht nicht gesondert erwähnt zu werden, dass ungefragtes Duzen in dieser Korrespondenz inakzeptabel ist (ich persönliche duze keine Studierende mit Ausnahme von eigenen Doktoranden und evtl. Hiwis; natürlich nur nach Absprache). Daher ist auch nicht sinnvoll, in der Grußformeln nur den eigenen Vornamen zu nennen.


## Was darf man sich erwarten?

Meine mittlere Anwortzeit liegt bei drei Tagen. Falls Sie das lange finden, bedenken Sie bitte, dass ich teilweise ganze Tage in die Lehre eingebunden bin, mitunter mehrere am Stück. Darüber hinaus ist mein Mailaufkommen oft sehr hoch. Schließlich finde ich, dass sich Professoren darin auszeichnen sollten, tief über Dinge nachzudenken -- wenn man den ganzen Tag auf seinen Posteingang schielt, kommt man mit dem tiefen Nachdenken nicht weit.

Bitte bedenken Sie, dass hochschulinterne Messaging-Systeme häufig keine Abwesenheitsnotiz zulassen (etwa um über Urlaub zu informieren). Daher ist eine Mail vorteilhafter; Sie dürfen erwarten, dass Sie über längere Abwesenheit mit einer entsprechenden Abwesenheitsnotiz informiert werden.

Ernsthafte Fragen verdienen einen Antwort und werden von mir eine erhalten.

