---
title: How to document a conference talk in citation manager software
author: Sebastian Sauer
date: '2019-06-28'
slug: how-to-document-a-conference-talk-in-citation-manager-software
categories:
  - science
tags:
  - reproducibility
---



```{r knitr-setup, echo = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  message = FALSE,
  warning = FALSE,
  cache = TRUE,
  out.width = "70%",
  fig.align = 'center',
  fig.width = 6,
  fig.asp = 0.618,  # 1 / phi
  fig.show = "hold",
  size = "tiny"
)
```




There are several popular citation manager software packages around. I used to work with Mendeley in class, but I stopped using it since it was acquired by El$sevier. Luckily there are good alternatives around, particularly Zotero. Zotero features a Word (MS Word, Libre Word) plugin, which is a must have for many of us. The more technically inclined folks will use Bibtex. Good news is that Zotero syncs it Library to Bibtex. Best of both worlds with Zotero -- I recommend using Zotero.

Some reasons why I like Zotero:

- [open source](https://github.com/zotero)
- free
- not part of money-sucking publishers
- a lot of great add-ons such as for RStudio
- bibtex support
- MS/Libre Word plugin


In this post, I'll show how to document your talk at a conference in Zotero.


The APA format tells us the the talk should be formatted as so:


>    Presenter, A. A. (Year, month). Title. Paper or poster session presented at the meeting of Organization X, Location.


Note that a *talk*  appears to be called a *paper*, and a poster is a *poster*.


# How to enter your talk details to Zotero

1. Go here: Menu > File > New Item > Presentation
Note that a talk can (and should, in Zotero) be mapped using the type `presentation` (see also [this post](https://forums.zotero.org/discussion/74130/proper-way-to-use-conference-name-and-proceedings-title)):


>   Zotero actually has two different entries for conference papers: (1) 'Presentation' should be used for the talk (or poster, etc.) itself, and then the conference name is important; and (2) 'Conference paper' should be used for a published paper in conference proceedings (but not just for a presentation). (This is confusing and I was informed about it on the forums recently: https://forums.zotero.org/discussion/8682/request-unified-style-sheet-for-linguistic-journals/ )



2. Insert your details
Note that `type` should be `paper` is you a indexing a talk held at a presentation.

Here's the standard output by Zotero:


>   Sauer, Sebastian. (2018, September). Reproduzierbares Schreiben in der Wissenschaft am Beispiel des Buchprojekts „Moderne Datenanalyse mit R“. Paper presented at the 51. Kongress der deutschen Gesellschaft für Psychologie, Frankfurt. Retrieved from https://www.dgpskongress.de/frontend/dgps/media/DGPs2018/DGPs2018_komplett_web.pdf


Pretty neat, right?


Note that Mendeley does *not* feature a type "presentation" or similar. Probably, the type `Generic` might help, but the standard output is not quite correct. There are surely ways to tweak that, but I'm not aware of an easygoing way (and not motivated to search, to be honest).



# Export

The most versatile export is to Bibtex. There are two ways Zotero will assist you with exporting to bibtex.


1. Go here: Menu > Preferences > Export > Quick Copy 
Choose Bibtex or Biblatex as export format. Than go back to your library, select one or more citations and press Cmd-Shift-C (Mac). The bibtex plain text will be copied to your clipboard. Using Cmd-V you will get back your bibtex cituation in the obvious way.

Here it is:

```
@misc{sauer_sebastian_reproduzierbares_2018,
	address = {Frankfurt},
	type = {Paper},
	title = {Reproduzierbares {Schreiben} in der {Wissenschaft} am {Beispiel} des {Buchprojekts} „{Moderne} {Datenanalyse} mit {R}“},
	url = {https://www.dgpskongress.de/frontend/dgps/media/DGPs2018/DGPs2018_komplett_web.pdf},
	author = {Sauer, Sebastian},
	month = sep,
	year = {2018}
}
```

Interestingly, Bibtex uses the `misc` type as well, but further clarifies that the type is a `paper`. However, the name of the conference is NOT transferred, which renders this output useless basically.



The Biblatex format further specifies a `howpublished` field, und uses the type `unpublished`. Unpublished makes sense as (in my case) only the abstract has been published by the society of the conference, but not a paper of the talk.

```
@unpublished{sauer_sebastian_reproduzierbares_2018,
	location = {Frankfurt},
	title = {Reproduzierbares Schreiben in der Wissenschaft am Beispiel des Buchprojekts „Moderne Datenanalyse mit R“},
	url = {https://www.dgpskongress.de/frontend/dgps/media/DGPs2018/DGPs2018_komplett_web.pdf},
	type = {Paper},
	howpublished = {Paper},
	note = {51. Kongress der deutschen Gesellschaft für Psychologie},
	author = {Sauer, Sebastian},
	date = {2018-09-18}
}
```

The Zotero plugin `BetterBibTex` further provides the `BetterBiblatex` format:

```
@unpublished{sauer_sebastian_reproduzierbares_2018,
  venue = {{Frankfurt}},
  title = {Reproduzierbares {{Schreiben}} in Der {{Wissenschaft}} Am {{Beispiel}} Des {{Buchprojekts}} „{{Moderne Datenanalyse}} Mit {{R}}“},
  url = {https://www.dgpskongress.de/frontend/dgps/media/DGPs2018/DGPs2018_komplett_web.pdf},
  type = {Paper},
  eventtitle = {51. {{Kongress}} Der Deutschen {{Gesellschaft}} Für {{Psychologie}}},
  date = {2018-09-18},
  author = {Sauer, Sebastian}
}
```



For the sake of curiosity, consider this bibtex export form Mendeley:


````
@misc{Sauer2019,
abstract = {Abstract test},
address = {N{\"{u}}rnberg},
author = {Sauer, Sebastian},
publisher = {42. Congress of Indifference},
title = {{Presentation title test}},
url = {www.some.url},
year = {2019}
}
````

BUT, although I have specified "type of work" is "Paper" in Mendely, this information is not carried over, for whatever reason.








