---
title: Crashkurs 'Umfrageforschung'
author: Sebastian Sauer
date: '2020-05-14'
slug: crashkurs-umfrageforschung
categories:
  - teaching
tags:
  - research
---



```{r knitr-setup, echo = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  message = FALSE,
  warning = FALSE,
  cache = TRUE,
  out.width = "70%",
  fig.align = 'center',
  fig.width = 6,
  fig.asp = 0.618,  # 1 / phi
  fig.show = "hold",
  size = "tiny"
)
```



#  Eine Einführung zur Erstellung, Durchführung und Auswertung von wissenschaftlich fundierten Fragebogen






# Lehr-Lern-Ziele

Die Teilnehmenden sollen befähigt werden, eine sozialwissenschaftlich fundierte Umfrage grundständig selbständig zu planen, durchzuführen und auszuwerten. Nebem dem Ziel der Kompetenz ist das Ziel der Selbstwirksamkeit zentral. Die Teilnehmenden sollen erfahren, dass es Ihnen (in grundständiger Variante) gut möglich ist, das Ziel zu erreichen, sich also als selbstwirksam zu erleben. 

Nicht Ziel ist es, tiefer gehende theoretische Konzepte zu vermitteln. Darüber hinaus muss das Curriculum aus Zeitgründen auf viele Inhalte verzichten. Durch Literaturhinweise soll dieses Manko in Teilen aufgefangen werden.

Klar betont werden muss, dass ein Kurs dieser Kürze kein breites Wissen vermitteln kann. Dementsprechend ist Kompetenz in einem eng begrenzten Curriculum verbunden mit dem Erleben von Selbstwirksamkeit das Ziel.


# Didaktisches Konzept

Der Crashkurs ist auf 2-3 Zeitstunden angesetzt, also sehr kurz. Auf Hintergründe und theoretische Konzepte muss weitgehend verzichtet werden. Im Vordergrund steht die Vermittlung von Kompetenz, im Sinne des "Wie-muss-ich-es-machen?". Daher besteht der Unterricht primär aus dem Vermitteln von Handlungskompetenz. Diese wird anhand zweier Methoden vermittelt: Erstens modellhaftes Vormachen und zweitens unterstütztes Selbermachen (seitens der Lernenden).

Der Kurs ist als Online-Seminar konzipiert. Es finden folgende Werkzeuge Verwendung: Video-Konferenz-Systeme (Zoom), Clicker-Abfragen (Mentimeter), Online-Whiteboard (Conceptboard), kollaboratitive Tabellenverarbeitung (Google Sheets). Im Gegensatz zu anderen vergleichbaren Kursen wird auf die Verwendung von Powerpoint-Folien u.Ä. verzichtet.

Die technische Hemmschwelle wird so tief wie möglich angesetzt: Die verwendeten Softwarepakete sind (für die Teilnehmenden) kostenfrei nutzbar und müssen nicht installiert werden, sondern sind "fertig" online nutzbar. Auf spezielle Statistik-Software (wie SPSS oder R) wird verzichtet, eben aus dem Grund die (technischen) Hürden so gering als möglich zu halten.

Es wird mit echten Daten gearbeitet und die Teilnehmer/innen (Ts) erstellen selber eine Umfrage und werten diese aus (im Rahmen der verfügbaren Zeit).


# Zielgruppe

Die Zielgruppe dieses Kurses lässt sich beschreiben als Lernende, die bisher kaum Kontakt zur empirischen Forschung hatten, allerdings einen Grund haben, sich damit auseinanderzusetzen. Dieser Grund kann in einem formalen Zwang (Prüfungsleistung der Hochschule) bestehen. Der Grund für die Beschäftigung kann aber auch am eigenen Anspruch oder Interesse zu suchen sein. Es wird davon ausgegangen, dass die Ts nicht über ein hohes Selbstwirksamkeitskonzept in der quantitatiuven Datenanalyse verfügen.


# Voraussetzungen zur Teilnahme

Zur Teilnahme am Kurs ist neben der Einwahl in das Webinar (und der damit verbundenen Internetverbindung) ein Konto bei Google sinnvoll (kostenlos und anonym anlegbar).




# Inhalte des Curriculums


## Organisatorisches (10 Min.)

- Begrüßung, Vorstellung der Lehrperson
- Lernziele, Nicht-Lernziele
- Ablauf/Inhalte
- Zur Relevanz des Themas: Warum quantitative Datenanalyse heute wichtig ist und wichtiger wird
- [Literaturhinweise](https://www.zotero.org/groups/2502975/ses-emp-fo/items)
- Beispiel für eine Umfrage: [Extraversionstest](https://forms.gle/Kcb1joSrqpeHEB7g9)


## Daten erheben (ca. 30 Min.)

- Für welche Art von Forschung ist Fragebogen-Forschung sinnvoll?
- Warum nicht selber einen Fragebogen "stricken"?
- Wo finde ich fertige wissenschaftlich fundierte Fragebogen?
	- [ZIS](https://zis.gesis.org/)
	- Validierungsbelege der Skalen 
- [Google Formulare](https://www.google.com/intl/de/forms/about/) als Umfragewerkzeug
	- Fragebogen von Gesis dort umsetzen
	- Ethik und Teilnahmerechte
- Ü: Ts erstellen selber einen Fragebogen (in Ansätzen)
- Ü: Ts füllen Fragebogen (via Link) anderer Ts aus


## Daten aufbereiten (ca. 30 Min.)

- Datensatz "Extra" von Google herunterladen/nach Google Sheets importieren:
	- [URL zum Google Sheet](https://docs.google.com/spreadsheets/d/1BiEyT3J5tp-VCuguXV40w6xStmsGS_jxcFd7zu1Cs0M/edit#gid=0)
 	- [URL zum CSV-Dokument](https://docs.google.com/spreadsheets/d/e/2PACX-1vRAt8c_zQpd-vhsQHQapnUyX-sEKtSP99oWhclp_JpJcySZMz037IA4ybdz3dRFOCLr6SjLbNSEb3tt/pub?gid=0&single=true&output=csv)  
- Typische Arbeitsschritte des Aufbereitens:
	- Items umkodieren
	- Scores (Zeilen-Mittelwerte) berechnen
- Daten visualisieren
	- Histogramm
	- Boxplot
- Daten grundständig auswerten
	- Mittelwerte (ohne Gruppierungen/Subgruppen)
- Ü: Ts bereiten Ihre Daten auf


## Daten auswerten (ca. 30 Min.)

- Mittelwerte pro Gruppe (mit G Sheets)
	- auswerten	
	- visualisieren 
- Korrelation
	- Kurz erklären
		- [Verdeutlichung der Korrelationsstärke](https://en.wikipedia.org/wiki/Correlation_and_dependence#/media/File:Correlation_examples2.svg)
	- berechnen
	- visualieren
- Ü: Ts berechnen Mittelwerte pro Gruppe und Korrelationen 


## Abschluss (ca. 30 Min.)

- Zusammenfassung
- Klärung offener Fragen



# Empfohlene Literatur und sonstige Quellen

Bortz, J., & Döring, N. (2006). Forschungsmethoden und Evaluation: Für Human- und Sozialwissenschaftler (4. Auflage). Springer. https://link.springer.com/book/10.1007/978-3-540-33306-7
Porst, R. (2014). Fragebogen: Ein Arbeitsbuch (4., erweiterte Auflage). Springer.
Sauer, S. (2019). Moderne Datenanalyse mit R: Daten einlesen, aufbereiten, visualisieren und modellieren (1. Auflage 2019). Springer. https://www.springer.com/de/book/9783658215866
ZIS Gesis: Open Access Repositorium für Messinstrumente. (2020, Mai 14). https://zis.gesis.org/


# Kontakt


Professor Sebastian Sauer, [Email](mailto:sebastiansauer1@gmail.com)
