---
title: Plotting equivalence class for confounder triangle
author: Sebastian Sauer
date: '2020-05-19'
slug: plotting-equivalence-class-for-confounder-triangle
categories:
  - DAG
  - causal
tags:
  - rstats
---



```{r knitr-setup, echo = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  message = FALSE,
  warning = FALSE,
  cache = TRUE,
  out.width = "70%",
  fig.align = 'center',
  fig.width = 6,
  fig.asp = 0.618,  # 1 / phi
  fig.show = "hold",
  size = "tiny"
)
```



# Load packages

```{r load-libs, message = FALSE, waring = FALSE}
library(tidyverse)
library(ggdag)
```





# Define DAG

```{r}
dag1_str <- 'dag {
  C [pos = "2,2"]
  X [exposure, pos = "1,1"] 
  Y [outcome, pos = "3,1"]
  C -> X
  C -> Y
}'


```



# Plot DAGs

First tidify:

```{r}
dag1 <- dagitty(dag1_str)

dag1_tidy <- tidy_dagitty(dag1)

dag1_tidy
```


Then plot:

```{r}
ggdag(dag1_tidy) + theme_dag()
```



# Equivalence class


```{r}

ggdag_equivalent_dags(confounder_triangle()) + theme_dag()

ggdag_equivalent_dags(dag1_tidy) + theme_dag()

```



