---
title: "Moderne Methoden der Wissenschaft:<br>"
subtitle: "Markdown und Git"
author: "<br><br> ifes/iwp | FOM | Sebastian Sauer"
#date: "2019-05-14"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["xaringan-themer.css", "my-css.css", "hygge"]
    seal: true 
    nature:
      titleSlideClass: ["right", "bottom", "test"]
      highlightStyle: solarized-dark
      highlightLines: true
      countIncrementalSlides: false

---


```{r xaringan-themer, include = FALSE}
library(xaringanthemer)

mono_light(
  base_color = "#23395b",
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "300", "300i"),
  code_font_google   = google_font("Droid Mono"),
  header_h1_font_size	= "50px",
  header_h2_font_size	= "30px",
  link_color = "ff9900"
)

```





```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```





```{r knitr-setup, echo = FALSE}



#knitr::opts_knit$set(
 # base.dir = base_dir,
  #base.url = base_url
#)

knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  warning = FALSE,
  cache = TRUE,
  out.width = "70%",
  fig.align = 'center',
  fig.width = 6,
  fig.asp =  0.618,  # 1 / phi
  fig.show = "hold",
  size = "tiny",
  dpi = 300,
  echo = FALSE #,
  #fig.path = fig_path
)
  

```

```{r libs}
library(tidyverse)
library(knitr)
library(DT)
library(gridExtra)
library(sessioninfo)
library(plotly)
library(here)
library(DiagrammeR)
library(DiagrammeRsvg)
library(DT)
library(mosaic)
```



```{r paths-setup}
proj_root <- here::here()
base_url <- "/"
fig_path <- "/imgs/"
```


```{r, load_refs, include=FALSE, cache=FALSE}
library(RefManageR)
BibOptions(check.entries = FALSE,
           bib.style = "authoryear",
           cite.style = "alphabetic",
           style = "markdown",
           hyperlink = FALSE,
           dashed = FALSE)
myBib <- ReadBib("input/bib.bib", check = FALSE)
```


class: middle

# Gliederung


1. Worum geht es hier eigentlich?

2. Markdown

3. Git

4. Fazit




---



```{r child = "chapters/part-repro.Rmd"}
```



```{r child = "chapters/part-md.Rmd"}
```



```{r child = "chapters/part-final.Rmd"}
```
